services:
  - type: web
    name: yt-audio-extractor
    env: python
    buildCommand: pip install -r backend/requirements.txt static-ffmpeg imageio-ffmpeg
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
